name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Fabric
        path: |
          fabric/build/libs/*.jar
          neoforge/build/libs/*.jar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NeoForge
        path: |
          neoforge/build/libs/*.jar
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: changelog.md
        draft: false
        prerelease: false
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar